# Generated by Django 6.0.1 on 2026-01-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_alter_productfeatures_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothings', 'Clothings'), ('jewelries', 'Jewelries'), ('groceries', 'Groceries'), ('unknown', 'Unknown')], default='unknown', max_length=40),
        ),
    ]
